language: node_js
services:
  - docker
env:
  global:
    - REGISTRY_USER="3ieregistry"
    # REGISTRY_PASS
    #- secure: "SECRET"
node_js:
  - 14
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.npm
  notifications:
    email:
      recipients:
        - kevin.bonnot@3ie.fr
        - jason.azoulay@3ie.fr
        - cedric.schneider@3ie.fr
      on_success: change
      on_failure: always
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install codecov -g
  - npm ci --ignore-scripts
script:
  # run build script specified in package.json
  - npm i webdriver-manager
  - npm run ci
  - docker build -f Dockerfile -t angular_ngrx_material_starter .
#before_deploy:
#  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin 3ieregistry.azurecr.io  
#deploy:
#  provider: script
#  script: bash deploy_to_repo.sh
#  on:
#    all_branches: true
#    condition: ${TRAVIS_BRANCH%%/*} != feature
after_success:
  - codecov
